#!/usr/bin/env python3
"""
Local LLM-as-music-critic.

We can't ship audio to a CI runner that has Ollama, so this script is
designed to run on your laptop:

    ollama pull llama3.1:8b   # or qwen2.5:14b, mistral-nemo, etc
    python scripts/judge_with_ollama.py \
        --audio-dir results/audio \
        --model llama3.1:8b \
        --out results/OLLAMA_REVIEW.md

Pipeline per audio file:
  1. Extract music-theory features (tempo, key, onset density, chroma,
     dynamics) via src.analysis.audio_features.
  2. Format the features as a structured prompt.
  3. POST to the local Ollama server at http://localhost:11434.
  4. Save the model's critique + 1–10 overall score.

The judge does *not* hear the actual audio (it sees the feature
summary), but for the kind of robotic / non-robotic distinction the
features cover (rhythmic regularity, dynamic range, key consistency,
spectral brightness, pitch-class diversity) the LLM can give a
remarkably useful critique.

To use the critique as a reward signal in training, see
src.analysis.ollama_reward (planned).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import time
from pathlib import Path
from typing import Dict, List

import urllib.error
import urllib.request

from src.analysis.audio_features import AudioFeatures, extract_directory


PROMPT_TEMPLATE = """\
You are an experienced music critic. You'll receive a *feature summary*
of a synthesized audio file generated by an experimental tabula-rasa
music model — no music data was used to train the model, only physics-
based psychoacoustic rewards (Sethares dissonance, Terhardt virtual
pitch, Large-Kolen rhythmic entrainment).

Your job is to (a) describe how the piece sounds based on the features,
(b) call out specifically what makes it feel robotic or alive, (c) give
two concrete suggestions for how to make it sound less synthetic, and
(d) give an overall score from 1 (unlistenable) to 10 (compelling
music). Reply in this exact format:

DESCRIPTION:
<one paragraph>

WHAT FEELS ROBOTIC:
- bullet
- bullet

CONCRETE FIXES:
- bullet
- bullet

SCORE: <integer 1-10>

----- FEATURES -----
{features}
----- END FEATURES -----
"""


def query_ollama(model: str, prompt: str,
                 host: str = "http://localhost:11434",
                 timeout: float = 120.0) -> str:
    body = json.dumps({
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": 0.4, "num_predict": 600},
    }).encode("utf-8")
    req = urllib.request.Request(
        f"{host}/api/generate",
        data=body,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = json.loads(resp.read())
    except urllib.error.URLError as e:
        raise SystemExit(
            f"Could not reach Ollama at {host} ({e}).\n"
            f"Start the server with `ollama serve` and pull a model "
            f"with `ollama pull {model}`."
        )
    return data.get("response", "")


def parse_score(text: str) -> int | None:
    m = re.search(r"SCORE:\s*(\d+)", text, re.IGNORECASE)
    if not m:
        return None
    s = int(m.group(1))
    return max(1, min(10, s))


def judge_one(features: AudioFeatures, model: str,
              host: str) -> Dict:
    prompt = PROMPT_TEMPLATE.format(features=features.text())
    response = query_ollama(model, prompt, host=host)
    return {
        "file": Path(features.path).name,
        "score": parse_score(response),
        "critique": response.strip(),
        "features": features.summary(),
    }


def write_report(results: List[Dict], out_path: Path,
                 model: str) -> None:
    lines = [
        "# Ollama music critique",
        "",
        f"Model: `{model}`",
        f"Files: {len(results)}",
        "",
        "## Scores",
        "",
        "| File | Score | Tempo | Key |",
        "|---|---|---|---|",
    ]
    for r in results:
        f = r["features"]
        lines.append(
            f"| `{r['file']}` | {r['score'] or '—'} / 10 | "
            f"{f['tempo_bpm']} BPM | {f['key']} |"
        )
    lines.extend(["", "## Per-file critiques", ""])
    for r in results:
        lines.append(f"### `{r['file']}`")
        lines.append("")
        lines.append("**Features:** " + ", ".join(
            f"{k}={v}" for k, v in r["features"].items()
            if k not in ("chroma_top3", "path")))
        lines.append("")
        lines.append("```")
        lines.append(r["critique"])
        lines.append("```")
        lines.append("")
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--audio-dir", default="results/audio")
    parser.add_argument("--model", default="llama3.1:8b",
                        help="any model `ollama pull`-ed locally")
    parser.add_argument("--host", default=os.environ.get(
        "OLLAMA_HOST", "http://localhost:11434"))
    parser.add_argument("--out", default="results/OLLAMA_REVIEW.md")
    parser.add_argument("--limit", type=int, default=None,
                        help="judge at most this many files (debugging)")
    args = parser.parse_args()

    print(f"extracting features from {args.audio_dir}...")
    feats = extract_directory(args.audio_dir)
    if args.limit:
        feats = feats[: args.limit]
    print(f"  {len(feats)} files")

    results = []
    for f in feats:
        print(f"judging {Path(f.path).name} via {args.model}...")
        t0 = time.time()
        try:
            r = judge_one(f, args.model, args.host)
        except SystemExit:
            raise
        except Exception as e:    # noqa: BLE001
            print(f"  ERROR: {e}")
            r = {"file": Path(f.path).name, "score": None,
                 "critique": f"(judge failed: {e})",
                 "features": f.summary()}
        results.append(r)
        print(f"  score={r['score']}  ({time.time() - t0:.1f}s)")

    write_report(results, Path(args.out), args.model)


if __name__ == "__main__":
    main()
