"""
Qwen2.5-Omni-as-music-critic: a multimodal LLM that listens to the
actual WAV (not a feature summary, like the Ollama judge does) and
returns a structured critique + 1-10 score.

Usable two ways:

  1. CLI — judge every WAV in a directory and write a JSON report.

         python -m src.analysis.qwen_judge \
             --audio-dir results/audio --limit 1 \
             --out results/QWEN_REVIEW.json

  2. Library — instantiate once, reuse as a reward signal in RLAIF.
     The model is large, so the singleton ``QwenJudge`` keeps it on
     device across many ``.score()`` calls.

         judge = QwenJudge(model="Qwen/Qwen2.5-Omni-7B", device="mps")
         result = judge.score_audio(audio_np, sample_rate=44100)
         #  -> {"score": 7, "critique": "...", "raw": "..."}

The prompt asks for the same four-section response shape as the
Ollama critic (DESCRIPTION / WHAT FEELS ROBOTIC / CONCRETE FIXES /
SCORE), so reports stay comparable.
"""
from __future__ import annotations

import argparse
import io
import json
import os
import re
import time
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional, Tuple

import numpy as np


_PROMPT = """\
You are an experienced music critic listening to a short audio clip
generated by an experimental "tabula-rasa" music model that was trained
with no music data — only physics-based psychoacoustic rewards
(Sethares dissonance, Terhardt virtual pitch, rhythmic entrainment).

Listen carefully. Then reply in this *exact* format:

DESCRIPTION:
<one paragraph: what does the piece actually sound like? pitch, rhythm,
mood, texture.>

WHAT FEELS ROBOTIC:
- <bullet>
- <bullet>

CONCRETE FIXES:
- <bullet>
- <bullet>

SCORE: <integer 1-10, where 1 = unlistenable noise, 5 = recognizably
musical but mechanical, 10 = compelling music>
"""


SCORE_RE = re.compile(r"SCORE\s*[:=]\s*(\d+)", re.IGNORECASE)
TARGET_SR = 16_000  # Qwen2.5-Omni expects 16 kHz mono


def _parse_score(text: str) -> Optional[int]:
    m = SCORE_RE.search(text)
    if not m:
        return None
    try:
        s = int(m.group(1))
    except ValueError:
        return None
    return max(1, min(10, s))


def _to_mono_16k(audio: np.ndarray, sample_rate: int) -> np.ndarray:
    """Convert any (T,) or (T, C) float audio to mono float32 at 16 kHz."""
    audio = np.asarray(audio)
    if audio.ndim == 2:
        audio = audio.mean(axis=1)
    audio = audio.astype(np.float32, copy=False)
    if sample_rate != TARGET_SR:
        import librosa
        audio = librosa.resample(audio, orig_sr=sample_rate,
                                 target_sr=TARGET_SR)
    # Hard clip to avoid +-inf surprising the processor.
    peak = float(np.max(np.abs(audio))) if audio.size else 1.0
    if peak > 1.0:
        audio = audio / peak
    return audio


def _load_wav(path: Path) -> Tuple[np.ndarray, int]:
    """Load a WAV → (mono float32 audio in [-1, 1], original sample_rate)."""
    import soundfile as sf
    a, sr = sf.read(str(path), dtype="float32", always_2d=False)
    if a.ndim == 2:
        a = a.mean(axis=1)
    return a.astype(np.float32, copy=False), int(sr)


# ----------------------------------------------------------------------


@dataclass
class JudgeResult:
    score: Optional[int]
    critique: str
    raw: str

    def to_dict(self) -> dict:
        return {"score": self.score, "critique": self.critique,
                "raw": self.raw}


_SYSTEM_PROMPT = (
    "You are Qwen, a virtual human developed by the Qwen Team, "
    "Alibaba Group, capable of perceiving auditory and visual inputs, "
    "as well as generating text and speech."
)


class QwenJudge:
    """Wrapper that loads Qwen2.5-Omni once and exposes ``.score_audio()``."""

    def __init__(self,
                 model: str = "Qwen/Qwen2.5-Omni-7B",
                 device: str = "mps",
                 dtype: str = "bfloat16",
                 attn_impl: str = "sdpa",
                 max_new_tokens: int = 280):
        self.model_name = model
        self.device = device
        self.max_new_tokens = max_new_tokens

        import torch

        torch_dtype = {
            "bfloat16": torch.bfloat16,
            "float16": torch.float16,
            "float32": torch.float32,
        }[dtype]
        self.dtype = torch_dtype

        # Try the canonical Qwen2.5-Omni classes first, fall back to
        # the generic Auto* classes if transformers is older.
        try:
            from transformers import (
                Qwen2_5OmniForConditionalGeneration as _Model,
                Qwen2_5OmniProcessor as _Processor,
            )
        except ImportError:    # pragma: no cover — fallback path
            from transformers import AutoProcessor as _Processor
            try:
                from transformers import AutoModelForMultimodalLM as _Model
            except ImportError:
                from transformers import AutoModel as _Model

        kw_attn = {"attn_implementation": attn_impl}
        try:
            self.model = _Model.from_pretrained(
                model, dtype=torch_dtype, **kw_attn,
            )
        except (TypeError, ValueError):
            # Older transformers used `torch_dtype` not `dtype`.
            self.model = _Model.from_pretrained(
                model, torch_dtype=torch_dtype, **kw_attn,
            )
        self.model = self.model.to(device)
        self.model.eval()
        self.processor = _Processor.from_pretrained(model)

        # Qwen2.5-Omni has a "Talker" submodule that only handles speech
        # output. We never ask it to speak, so drop it (frees ~2 GB).
        if hasattr(self.model, "disable_talker"):
            try:
                self.model.disable_talker()
            except Exception:
                pass

        self._torch = torch
        warnings.filterwarnings(
            "ignore",
            message=".*video does not match.*",
            module="transformers",
        )

    # ------------------------------------------------------------------

    def _generate(self, audio: np.ndarray) -> str:
        """Run a single chat-template generation on a mono 16k audio."""
        torch = self._torch
        # Conversation matches the upstream Qwen2.5-Omni example exactly.
        conversation = [
            {"role": "system",
             "content": [{"type": "text", "text": _SYSTEM_PROMPT}]},
            {"role": "user",
             "content": [
                 {"type": "text", "text": _PROMPT},
                 {"type": "audio", "audio": audio},
             ]},
        ]

        # process_mm_info handles numpy arrays directly (no resampling
        # — the array is assumed to already be 16 kHz mono float).
        from qwen_omni_utils import process_mm_info
        text = self.processor.apply_chat_template(
            conversation, add_generation_prompt=True, tokenize=False,
        )
        audios, images, videos = process_mm_info(
            conversation, use_audio_in_video=False,
        )
        inputs = self.processor(
            text=text, audio=audios, images=images, videos=videos,
            return_tensors="pt", padding=True, use_audio_in_video=False,
        )
        # Cast tensors to device + model dtype.
        moved = {}
        for k, v in inputs.items():
            if isinstance(v, torch.Tensor):
                if v.is_floating_point():
                    moved[k] = v.to(self.device, dtype=self.dtype)
                else:
                    moved[k] = v.to(self.device)
            else:
                moved[k] = v
        inputs = moved

        with torch.no_grad():
            try:
                gen = self.model.generate(
                    **inputs,
                    use_audio_in_video=False,
                    return_audio=False,
                    max_new_tokens=self.max_new_tokens,
                    do_sample=False,
                )
            except TypeError:
                gen = self.model.generate(
                    **inputs,
                    max_new_tokens=self.max_new_tokens,
                    do_sample=False,
                )

        if isinstance(gen, (list, tuple)):
            gen = gen[0]
        input_len = inputs["input_ids"].shape[1] if "input_ids" in inputs else 0
        out_ids = gen[:, input_len:] if input_len else gen
        text = self.processor.batch_decode(
            out_ids, skip_special_tokens=True,
            clean_up_tokenization_spaces=False,
        )[0]
        return text.strip()

    # ------------------------------------------------------------------

    def score_audio(self, audio: np.ndarray,
                    sample_rate: int = 44_100) -> JudgeResult:
        """Score a mono float audio array in [-1, 1]."""
        a16 = _to_mono_16k(audio, sample_rate)
        raw = self._generate(a16)
        return JudgeResult(score=_parse_score(raw),
                           critique=raw, raw=raw)

    def score_file(self, path: str | Path) -> JudgeResult:
        audio, sr = _load_wav(Path(path))
        return self.score_audio(audio, sample_rate=sr)


# ----- batch / CLI ----------------------------------------------------


def _iter_wavs(audio_dir: Path) -> List[Path]:
    return sorted(p for p in audio_dir.glob("*.wav"))


def judge_directory(audio_dir: Path,
                    out_path: Path,
                    model: str = "Qwen/Qwen2.5-Omni-7B",
                    device: str = "mps",
                    limit: Optional[int] = None) -> dict:
    paths = _iter_wavs(audio_dir)
    if limit is not None:
        paths = paths[:limit]
    print(f"judging {len(paths)} clips with {model} on {device}...",
          flush=True)
    judge = QwenJudge(model=model, device=device)

    results = []
    t_start = time.time()
    for i, p in enumerate(paths):
        t0 = time.time()
        try:
            r = judge.score_file(p)
        except Exception as e:    # noqa: BLE001
            print(f"  [{i+1}/{len(paths)}] {p.name}: ERROR {e!r}",
                  flush=True)
            r = JudgeResult(score=None,
                            critique=f"(judge failed: {e!r})",
                            raw=f"ERROR {e!r}")
        results.append({"file": p.name, **r.to_dict()})
        dt = time.time() - t0
        score_str = f"{r.score}/10" if r.score is not None else "—"
        print(f"  [{i+1}/{len(paths)}] {p.name}  score={score_str}  "
              f"({dt:.1f}s)", flush=True)
        # Stream-write so we don't lose progress on long runs.
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps({
            "model": model,
            "device": device,
            "results": results,
        }, indent=2))

    summary = {
        "model": model,
        "device": device,
        "n_clips": len(results),
        "mean_score": (sum(r["score"] for r in results
                           if isinstance(r["score"], int))
                       / max(1, sum(1 for r in results
                                    if isinstance(r["score"], int)))),
        "elapsed_sec": round(time.time() - t_start, 1),
        "results": results,
    }
    out_path.write_text(json.dumps(summary, indent=2))
    print(f"wrote {out_path} ({summary['elapsed_sec']}s, "
          f"mean={summary['mean_score']:.2f})", flush=True)
    return summary


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--audio-dir", default="results/audio")
    p.add_argument("--out", default="results/QWEN_REVIEW.json")
    p.add_argument("--qwen-model", default="Qwen/Qwen2.5-Omni-7B")
    p.add_argument("--qwen-device", default=os.environ.get(
        "QWEN_DEVICE", "mps"))
    p.add_argument("--limit", type=int, default=None)
    args = p.parse_args()

    judge_directory(
        audio_dir=Path(args.audio_dir),
        out_path=Path(args.out),
        model=args.qwen_model,
        device=args.qwen_device,
        limit=args.limit,
    )


if __name__ == "__main__":
    main()
